# Generated by Django 5.1.6 on 2025-03-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='type',
            field=models.CharField(choices=[('Personal Trainer', 'Personal Trainer'), ('Group Fitness Instructor', 'Group Fitness Instructor'), ('Strength & Conditioning Coach', 'Strength & Conditioning Coach'), ('Weightlifting & Bodybuilding Coach', 'Weightlifting & Bodybuilding Coach'), ('Cardio Trainer ', 'Cardio Trainer '), ('Rehabilitation & Injury Recovery Trainer', 'Rehabilitation & Injury Recovery Trainer'), ('Sports-Specific Trainer', 'Sports-Specific Trainer'), ('Functional Fitness Trainer', 'Functional Fitness Trainer'), ('Senior Fitness Trainer', 'Senior Fitness Trainer'), ('Yoga & Pilates Instructor', 'Yoga & Pilates Instructor'), ('Nutrition & Wellness Coach', 'Nutrition & Wellness Coach')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
