# Generated by Django 5.1.6 on 2025-03-26 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_trainer_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Beginners ', 'Beginners '), ('Casual Gym-Goers', 'Casual Gym-Goers'), ('Fitness Enthusiasts', 'Fitness Enthusiasts'), ('Bodybuilders & Strength Trainers', 'Bodybuilders & Strength Trainers'), ('Weight Loss Seekers ', 'Weight Loss Seekers '), ('Athletes & Sports-Specific Trainers', 'Athletes & Sports-Specific Trainers'), ('Group Class Participants', 'Group Class Participants'), ('Seniors & Special Needs Members', 'Seniors & Special Needs Members'), ('Rehabilitation & Recovery Members', 'Rehabilitation & Recovery Members'), ('Hardcore Fitness Addicts', 'Hardcore Fitness Addicts')], max_length=100)),
                ('plan', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.trainer')),
            ],
        ),
    ]
