# Generated by Django 5.1.6 on 2025-03-26 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_workoutplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.member'),
            preserve_default=False,
        ),
    ]
