# Generated by Django 5.1.6 on 2025-03-26 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_workoutplan_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='selectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.trainer')),
            ],
        ),
    ]
