# Generated by Django 5.1.6 on 2025-04-23 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_selectstatus_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=250)),
                ('picture', models.ImageField(upload_to='Community_picture/')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.member')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.trainer')),
            ],
        ),
    ]
