# Generated by Django 5.1.6 on 2025-04-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='Community_picture/'),
        ),
    ]
