# Generated by Django 5.1.6 on 2025-04-23 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_community_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.member'),
        ),
        migrations.AlterField(
            model_name='community',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.trainer'),
        ),
    ]
