# Generated by Django 5.1.6 on 2025-04-30 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_community_member_alter_community_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectstatus',
            name='palnStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.workoutplan'),
            preserve_default=False,
        ),
    ]
