# Generated by Django 5.1.6 on 2025-04-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_selectstatus_palnstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectstatus',
            name='palnStatus',
        ),
    ]
